---
- name: my playbook of installing and starting httpd
  hosts: all
  become: true
  tasks:
          - name: installing httpd
            yum:
                    name: httpd
                    state: installed
            when: ansible_os_family == "RedHat"

          - name: starting htt..
            service:
                    name: httpd
                    state: started
            when: ansible_os_family == "RedHat"

          - name: installing apache2
            apt:
                    name: apache2
                    state: present
            when: ansible_os_family == "Debian"

          - name: starting apache
            service:
                    name: apache2
                    state: started
            when: ansible_os_family == "Debian"

          - name: copy fileweb
            copy: 
              src: /home/ansadmin/index.html
              dest: /var/www/html
              mode: 0666  


