---
- name: playbook of tomcat
  hosts: webboy
  become: true
  tasks:
          - name: installing java
            yum: 
              name: java
              state: installed
            when: ansible_os_family == "RedHat"

          - name: downloading tomcat
            get_url:
                    url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.66/bin/apache-tomcat-8.5.66.tar.gz
                    dest: /opt

          - name: extracting tomcat
            unarchive:
                    src: /opt/apache-tomcat-8.5.66.tar.gz
                    dest: /opt
                    remote_src: yes

          - name: giving permissions
            file:
                    path: /opt/apache-tomcat-8.5.66/bin/startup.sh
                    mode: 0777

          - name: starting service
            shell: nohup ./startup.sh
            args:
                    chdir: /opt/apache-tomcat-8.5.66/bin




        
